version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/ceh_timetable
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    restart: unless-stopped

  db:
    image: registry.redhat.io/rhel8/postgresql-13:latest
    environment:
      - POSTGRESQL_DATABASE=ceh_timetable
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_ADMIN_PASSWORD=adminpassword
    volumes:
      - postgres_data_dev:/var/lib/pgsql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ceh_timetable"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
    driver: local

networks:
  default:
    driver: bridge
